{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOAHu8SoXG6GRaJAsyFTQXA",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/michalziga/news-scraper-1/blob/main/newsscraper.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 12,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "PH0ZO5ULJrUH",
        "outputId": "ef8ce4af-9f37-4d6f-ee0b-3ff126e4fc5e"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: lxml_html_clean in /usr/local/lib/python3.12/dist-packages (0.4.4)\n",
            "Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from lxml_html_clean) (6.0.2)\n"
          ]
        }
      ],
      "source": [
        "!pip install lxml_html_clean"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install feedparser\n",
        "!pip install newspaper3k\n",
        "!pip install requests\n",
        "!pip install beautifulsoup4"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "vgo_hNATNhVO",
        "outputId": "c719b97b-1dc8-45d9-a309-cccee4da3c00"
      },
      "execution_count": 13,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: feedparser in /usr/local/lib/python3.12/dist-packages (6.0.12)\n",
            "Requirement already satisfied: sgmllib3k in /usr/local/lib/python3.12/dist-packages (from feedparser) (1.0.0)\n",
            "Requirement already satisfied: newspaper3k in /usr/local/lib/python3.12/dist-packages (0.2.8)\n",
            "Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (4.13.5)\n",
            "Requirement already satisfied: Pillow>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (11.3.0)\n",
            "Requirement already satisfied: PyYAML>=3.11 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (6.0.3)\n",
            "Requirement already satisfied: cssselect>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (1.4.0)\n",
            "Requirement already satisfied: lxml>=3.6.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (6.0.2)\n",
            "Requirement already satisfied: nltk>=3.2.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (3.9.1)\n",
            "Requirement already satisfied: requests>=2.10.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (2.32.4)\n",
            "Requirement already satisfied: feedparser>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (6.0.12)\n",
            "Requirement already satisfied: tldextract>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (5.3.1)\n",
            "Requirement already satisfied: feedfinder2>=0.0.4 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.0.4)\n",
            "Requirement already satisfied: jieba3k>=0.35.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.35.1)\n",
            "Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (2.9.0.post0)\n",
            "Requirement already satisfied: tinysegmenter==0.3 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (0.3)\n",
            "Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->newspaper3k) (2.8.3)\n",
            "Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->newspaper3k) (4.15.0)\n",
            "Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from feedfinder2>=0.0.4->newspaper3k) (1.17.0)\n",
            "Requirement already satisfied: sgmllib3k in /usr/local/lib/python3.12/dist-packages (from feedparser>=5.2.1->newspaper3k) (1.0.0)\n",
            "Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (8.3.1)\n",
            "Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (1.5.3)\n",
            "Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (2025.11.3)\n",
            "Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (4.67.3)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (3.4.4)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (3.11)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (2.5.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (2026.2.25)\n",
            "Requirement already satisfied: requests-file>=1.4 in /usr/local/lib/python3.12/dist-packages (from tldextract>=2.0.1->newspaper3k) (3.0.1)\n",
            "Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.12/dist-packages (from tldextract>=2.0.1->newspaper3k) (3.24.3)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)\n",
            "Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)\n",
            "Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)\n",
            "Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import feedparser\n",
        "from newspaper import Article\n",
        "import time"
      ],
      "metadata": {
        "id": "MPHELV4AY1cF"
      },
      "execution_count": 14,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "keywords = [\"war\", \"Iran\", \"IRGC\", \"US\", \"Israel\"]\n",
        "\n",
        "feeds = [\n",
        "    \"https://www.aktuality.sk/rss/\",\n",
        "    \"https://www.reuters.com/world/rss\",\n",
        "    \"https://feeds.bbci.co.uk/news/world/rss.xml\"\n",
        "]"
      ],
      "metadata": {
        "id": "brIzVZMuY4GH"
      },
      "execution_count": 15,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "def contains_keywords(text, keywords):\n",
        "    if text is None:\n",
        "        return False\n",
        "\n",
        "    text_lower = text.lower()\n",
        "    for keyword in keywords:\n",
        "        if keyword.lower() in text_lower:\n",
        "            return True\n",
        "    return False"
      ],
      "metadata": {
        "id": "Q3yKIr5yY67Z"
      },
      "execution_count": 16,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "def get_article_text(url, timeout=10):\n",
        "    try:\n",
        "        article = Article(url)\n",
        "        article.download()\n",
        "        article.parse()\n",
        "        return {\n",
        "            \"title\": article.title,\n",
        "            \"text\": article.text,\n",
        "            \"authors\": article.authors\n",
        "        }\n",
        "    except Exception as e:\n",
        "        print(f\" [ERROR] Could not exctract article: {str(e)}\")\n",
        "        return None\n"
      ],
      "metadata": {
        "id": "9indV6QiY926"
      },
      "execution_count": 17,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "def scrape_news():\n",
        "    all_articles = []\n",
        "\n",
        "    for feed_url in feeds:\n",
        "        print(f\"\\n Parsing feed: {feed_url}\")\n",
        "        print(f\"-\" * 60)\n",
        "\n",
        "        try:\n",
        "            feed = feedparser.parse(feed_url)\n",
        "\n",
        "            for entry in feed.entries[:50]:\n",
        "                title = entry.get(\"title\",\"No title\")\n",
        "                link = entry.get(\"link\",\"No link\")\n",
        "                summary = entry.get(\"summary\",\"\")\n",
        "\n",
        "                if contains_keywords(title, keywords) or contains_keywords(summary,keywords):\n",
        "                    print(f\"\\n Found matching article: {title}\")\n",
        "                    print(f\"    URL: {link}\")\n",
        "\n",
        "                    print(f\"    Extracting full text ...\")\n",
        "                    article_data = get_article_text(link)\n",
        "\n",
        "                    if article_data:\n",
        "                        all_articles.append({\n",
        "                            \"title\": title,\n",
        "                            \"url\": link,\n",
        "                            \"full_text\": article_data[\"text\"],\n",
        "                            \"authors\": article_data[\"authors\"]\n",
        "                        })\n",
        "                        text_preview = article_data[\"text\"][:200]+\"...\"\n",
        "                        print(f\"    Preview: {text_preview}\")\n",
        "                        print(\"     \"+\"-\"*55)\n",
        "                    time.sleep(2)\n",
        "        except Exception as e:\n",
        "            print(f\"[ERROR] parsing feed {feed_url}:{str(e)}\")\n",
        "            time.sleep(1)\n",
        "    return all_articles\n"
      ],
      "metadata": {
        "id": "YtFfdkjwObBv"
      },
      "execution_count": 18,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "if __name__ == \"__main__\":\n",
        "    print(\"=\" * 60)\n",
        "    print(\"NEWS SCRAPER - Finding articles about:\", ', '.join(keywords))\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "    # Run the scraper\n",
        "    articles = scrape_news()\n",
        "\n",
        "    # Display results\n",
        "    print(\"\\n\" + \"=\" * 60)\n",
        "    print(f\"📊 RESULTS: Found {len(articles)} matching articles\")\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "    for i, article in enumerate(articles, 1):\n",
        "        print(f\"\\n{i}. {article['title']}\")\n",
        "        print(f\"   URL: {article['url']}\")\n",
        "        if article['authors']:\n",
        "            print(f\"   By: {', '.join(article['authors'])}\")\n",
        "        print(f\"   Text preview: {article['full_text'][:150]}...\")\n",
        "        print(\"-\" * 60)\n",
        "\n",
        "    print(\"\\n✨ Scraping complete!\")"
      ],
      "metadata": {
        "id": "3tKPTB6wYvj8",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "723a7228-01ad-420d-a265-323a2b6b59db"
      },
      "execution_count": 19,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "============================================================\n",
            "NEWS SCRAPER - Finding articles about: war, Iran, IRGC, US, Israel\n",
            "============================================================\n",
            "\n",
            " Parsing feed: https://www.aktuality.sk/rss/\n",
            "------------------------------------------------------------\n",
            "\n",
            " Found matching article: Emmanuel Macron mieri na Cyprus: Francúzsko na ostrov po útokoch dronov posiela lietadlovú loď Charles de Gaulle\n",
            "    URL: https://www.aktuality.sk/clanok/vrpoeEj/emmanuel-macron-mieri-na-cyprus-francuzsko-na-ostrov-po-utokoch-dronov-posiela-lietadlovu-lod-charles-de-gaulle/\n",
            "    Extracting full text ...\n",
            "    Preview: ...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: Iránske Zhromaždenie znalcov úspešne zvolilo nového najvyššieho vodcu\n",
            "    URL: https://www.aktuality.sk/clanok/7fx207V/iran-ma-noveho-najvyssieho-vodcu-meno-vsak-teheran-zatial-drzi-v-tajnosti/\n",
            "    Extracting full text ...\n",
            "    Preview: ...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: Severozápad Grécka ráno zasiahlo zemetrasenie s magnitúdou 5,3\n",
            "    URL: https://www.aktuality.sk/clanok/5bVW0v1/severozapadne-grecko-zasiahlo-zemetrasenie-otrasy-s-magnitudou-53-vystrasili-aj-korfu/\n",
            "    Extracting full text ...\n",
            "    Preview: ...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: Na čerpacej stanici pri Novom Meste nad Váhom prišiel pod kolesami auta o život len 4-ročný chlapec\n",
            "    URL: https://www.aktuality.sk/clanok/r6g4c6X/tragedia-na-povazi-na-cerpacej-stanici-prisiel-pod-kolesami-auta-o-zivot-len-4-rocny-chlapec/\n",
            "    Extracting full text ...\n",
            "    Preview: ...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: Repatriačné lety pokračujú: Slovensko v sobotu prepravilo do bezpečia ďalších 115 ľudí z Rijádu a Maskatu\n",
            "    URL: https://www.aktuality.sk/clanok/yToZWvf/slovensko-ma-za-sebou-uz-12-repatriacnych-letov-v-sobotu-pristalo-doma-dalsich-102-slovakov/\n",
            "    Extracting full text ...\n",
            "    Preview: ...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: Spojené štáty a Izrael v noci vystupňovali svoju ofenzívu priamymi údermi na ropný priemysel v Teheráne\n",
            "    URL: https://www.aktuality.sk/clanok/5OCnWXo/nocne-nalety-na-teheran-usa-a-izrael-zasiahli-pat-klucovych-ropnych-zariadeni/\n",
            "    Extracting full text ...\n",
            "    Preview: ...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Parsing feed: https://www.reuters.com/world/rss\n",
            "------------------------------------------------------------\n",
            "\n",
            " Parsing feed: https://feeds.bbci.co.uk/news/world/rss.xml\n",
            "------------------------------------------------------------\n",
            "\n",
            " Found matching article: Dozens killed as Israeli special forces raid Lebanese village in search of 40-year-old remains\n",
            "    URL: https://www.bbc.com/news/articles/cy8l2p2l3v0o?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: \"My uncle is a retired soldier, his son is also a retired soldier and his other son is a school teacher. We are not affiliated with any political party. We are Shia - we like Hezbollah, but we are not...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: War fuels debate in Cyprus over UK military bases\n",
            "    URL: https://www.bbc.com/news/articles/cx2r1xldl1ko?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: \"But I believe this is a conversation that one needs to have after we have a careful reflection as to what has transpired, especially in recent days and hours,\" he told BBC Newsnight....\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: US embassy in Oslo hit by explosion, Norway police say\n",
            "    URL: https://www.bbc.com/news/articles/c5yjegg892lo?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: He said the police had also issued an appeal for information from anyone who may have seen or heard anything about the incident....\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: Boy, 12, among six dead as tornadoes hit Michigan and Oklahoma\n",
            "    URL: https://www.bbc.com/news/articles/crrxpwzvd5vo?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: \"We look out the window and saw the tornado go right down the strip and that's where my daughter is, where my parents, where I live down the road,\" a Three Rivers, Michigan resident told the BBC's US ...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: Iranian ambassador warns UK to be 'very careful' about further involvement in war\n",
            "    URL: https://www.bbc.com/news/articles/cq6qp458zv1o?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: \"If the aggression… continues there is no doubt we will defend ourselves,\" he said. \"And if they want to use these military bases - although we don't want to do that - there is no doubt we will defend...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: Swiss to vote on right-wing push to slash licence fee for public broadcaster\n",
            "    URL: https://www.bbc.com/news/articles/c4g55v24wrno?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: Members of the committee leading the campaign to cut the licence fee say they had nothing to do with the RT piece, no contact with Russian media and do not agree with the accusation that SBC journalis...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: Russian strike on Kharkiv apartment block kills ten\n",
            "    URL: https://www.bbc.com/news/articles/cn8zd049l08o?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: US asked Ukraine for help fighting Iranian drones, Zelensky says\n",
            "\n",
            "Ukraine's president says Kyiv will only help if doing so does not deplete its own air defences....\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: Armed robots take to the battlefield in Ukraine war\n",
            "    URL: https://www.bbc.com/news/articles/c62662gzlp8o?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: \"Sooner or later, we'll end up in a situation where our strike UGV will come up against their strike UGV on the battlefield. Robot wars may sound like science fiction, but there's nothing sci-fi about...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: China spent years building ties in Latin America. Can Trump make room for the US?\n",
            "    URL: https://www.bbc.com/news/articles/c5yvw0zwpd5o?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: The Trump administration has said Saturday's summit aims to \"enlist and expand\" US friends in the Western Hemisphere and limit Chinese engagement across the Americas, including moving to prevent rival...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: Indonesia to ban social media and other online platforms for under 16s\n",
            "    URL: https://www.bbc.com/news/articles/cvg50168ddgo?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: Indonesia preparing to deploy up to 8,000 soldiers to Gaza\n",
            "\n",
            "It would be the first country to do so as part of phase two of the ceasefire agreement brokered by the US last year....\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: US and Venezuela agree to resume diplomatic ties after Maduro capture\n",
            "    URL: https://www.bbc.com/news/articles/cy9g1l5jx90o?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: After a visit to Venezuela, US Secretary of the Interior Doug Burgum told reporters on the runway in Caracas on Thursday on his way back to the US that it was a \"brilliant strategic move\" to intervene...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: We've been speaking to Iranians during one week of war. Here's what they said\n",
            "    URL: https://www.bbc.com/news/articles/c5y5lqygrn7o?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: My colleague Ghoncheh Habibiazad, who has been collecting voices from inside the country, says the views of some people have changed as the war has continued, as they did not expect it to go on after ...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: The heartwarming tale of a father, a daughter, and a wedding band wowing India\n",
            "    URL: https://www.bbc.com/news/articles/c7430kn9ze4o?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: \"It's not a matter of shame for the father,\" Rao says. \"He wants to welcome her back with the same pomp and show with which he had sent her off. By celebrating her return, he's showing his pride that ...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: The final voyage of the Iranian warship sunk by the US\n",
            "    URL: https://www.bbc.com/news/articles/c4geelnw7w3o?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: \"What happened next is less clear: the ship may have returned to port or peeled away after exercises. Either way, the waters where it was later sunk - off Galle in Sri Lanka - lie only two to three da...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: AI-generated Iran war videos surge as creators use new tech to cash in\n",
            "    URL: https://www.bbc.com/news/articles/ckg8wvz427vo?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: Experts have told BBC Verify that while many social media companies say they are trying to change their moderation and detection systems to address the scale and speed at which AI-generated content sp...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: Beirut evacuees 'sleeping in tents and cars'\n",
            "    URL: https://www.bbc.com/news/videos/cg4g0gl23z4o?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: In Lebanon, some residents in the southern Beirut suburb of Dahieh have left their homes amid evacuation orders and ongoing air strikes by Israel.\n",
            "\n",
            "BBC Arabic's Carine Torbey says people from the area...\n",
            "     -------------------------------------------------------\n",
            "\n",
            " Found matching article: After Iran, will Trump turn his eyes to Cuba?\n",
            "    URL: https://www.bbc.com/news/videos/c4gq8yd3qlxo?at_medium=RSS&at_campaign=rss\n",
            "    Extracting full text ...\n",
            "    Preview: Donald Trump's attention is seemingly turning to another Latin American regime: Cuba.\n",
            "\n",
            "In recent months, the president has hinted at a possible takeover and during a White House event with the Inter M...\n",
            "     -------------------------------------------------------\n",
            "\n",
            "============================================================\n",
            "📊 RESULTS: Found 23 matching articles\n",
            "============================================================\n",
            "\n",
            "1. Emmanuel Macron mieri na Cyprus: Francúzsko na ostrov po útokoch dronov posiela lietadlovú loď Charles de Gaulle\n",
            "   URL: https://www.aktuality.sk/clanok/vrpoeEj/emmanuel-macron-mieri-na-cyprus-francuzsko-na-ostrov-po-utokoch-dronov-posiela-lietadlovu-lod-charles-de-gaulle/\n",
            "   Text preview: ...\n",
            "------------------------------------------------------------\n",
            "\n",
            "2. Iránske Zhromaždenie znalcov úspešne zvolilo nového najvyššieho vodcu\n",
            "   URL: https://www.aktuality.sk/clanok/7fx207V/iran-ma-noveho-najvyssieho-vodcu-meno-vsak-teheran-zatial-drzi-v-tajnosti/\n",
            "   Text preview: ...\n",
            "------------------------------------------------------------\n",
            "\n",
            "3. Severozápad Grécka ráno zasiahlo zemetrasenie s magnitúdou 5,3\n",
            "   URL: https://www.aktuality.sk/clanok/5bVW0v1/severozapadne-grecko-zasiahlo-zemetrasenie-otrasy-s-magnitudou-53-vystrasili-aj-korfu/\n",
            "   Text preview: ...\n",
            "------------------------------------------------------------\n",
            "\n",
            "4. Na čerpacej stanici pri Novom Meste nad Váhom prišiel pod kolesami auta o život len 4-ročný chlapec\n",
            "   URL: https://www.aktuality.sk/clanok/r6g4c6X/tragedia-na-povazi-na-cerpacej-stanici-prisiel-pod-kolesami-auta-o-zivot-len-4-rocny-chlapec/\n",
            "   Text preview: ...\n",
            "------------------------------------------------------------\n",
            "\n",
            "5. Repatriačné lety pokračujú: Slovensko v sobotu prepravilo do bezpečia ďalších 115 ľudí z Rijádu a Maskatu\n",
            "   URL: https://www.aktuality.sk/clanok/yToZWvf/slovensko-ma-za-sebou-uz-12-repatriacnych-letov-v-sobotu-pristalo-doma-dalsich-102-slovakov/\n",
            "   Text preview: ...\n",
            "------------------------------------------------------------\n",
            "\n",
            "6. Spojené štáty a Izrael v noci vystupňovali svoju ofenzívu priamymi údermi na ropný priemysel v Teheráne\n",
            "   URL: https://www.aktuality.sk/clanok/5OCnWXo/nocne-nalety-na-teheran-usa-a-izrael-zasiahli-pat-klucovych-ropnych-zariadeni/\n",
            "   Text preview: ...\n",
            "------------------------------------------------------------\n",
            "\n",
            "7. Dozens killed as Israeli special forces raid Lebanese village in search of 40-year-old remains\n",
            "   URL: https://www.bbc.com/news/articles/cy8l2p2l3v0o?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: \"My uncle is a retired soldier, his son is also a retired soldier and his other son is a school teacher. We are not affiliated with any political part...\n",
            "------------------------------------------------------------\n",
            "\n",
            "8. War fuels debate in Cyprus over UK military bases\n",
            "   URL: https://www.bbc.com/news/articles/cx2r1xldl1ko?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: \"But I believe this is a conversation that one needs to have after we have a careful reflection as to what has transpired, especially in recent days a...\n",
            "------------------------------------------------------------\n",
            "\n",
            "9. US embassy in Oslo hit by explosion, Norway police say\n",
            "   URL: https://www.bbc.com/news/articles/c5yjegg892lo?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: He said the police had also issued an appeal for information from anyone who may have seen or heard anything about the incident....\n",
            "------------------------------------------------------------\n",
            "\n",
            "10. Boy, 12, among six dead as tornadoes hit Michigan and Oklahoma\n",
            "   URL: https://www.bbc.com/news/articles/crrxpwzvd5vo?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: \"We look out the window and saw the tornado go right down the strip and that's where my daughter is, where my parents, where I live down the road,\" a ...\n",
            "------------------------------------------------------------\n",
            "\n",
            "11. Iranian ambassador warns UK to be 'very careful' about further involvement in war\n",
            "   URL: https://www.bbc.com/news/articles/cq6qp458zv1o?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: \"If the aggression… continues there is no doubt we will defend ourselves,\" he said. \"And if they want to use these military bases - although we don't ...\n",
            "------------------------------------------------------------\n",
            "\n",
            "12. Swiss to vote on right-wing push to slash licence fee for public broadcaster\n",
            "   URL: https://www.bbc.com/news/articles/c4g55v24wrno?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: Members of the committee leading the campaign to cut the licence fee say they had nothing to do with the RT piece, no contact with Russian media and d...\n",
            "------------------------------------------------------------\n",
            "\n",
            "13. Russian strike on Kharkiv apartment block kills ten\n",
            "   URL: https://www.bbc.com/news/articles/cn8zd049l08o?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: US asked Ukraine for help fighting Iranian drones, Zelensky says\n",
            "\n",
            "Ukraine's president says Kyiv will only help if doing so does not deplete its own ai...\n",
            "------------------------------------------------------------\n",
            "\n",
            "14. Armed robots take to the battlefield in Ukraine war\n",
            "   URL: https://www.bbc.com/news/articles/c62662gzlp8o?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: \"Sooner or later, we'll end up in a situation where our strike UGV will come up against their strike UGV on the battlefield. Robot wars may sound like...\n",
            "------------------------------------------------------------\n",
            "\n",
            "15. China spent years building ties in Latin America. Can Trump make room for the US?\n",
            "   URL: https://www.bbc.com/news/articles/c5yvw0zwpd5o?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: The Trump administration has said Saturday's summit aims to \"enlist and expand\" US friends in the Western Hemisphere and limit Chinese engagement acro...\n",
            "------------------------------------------------------------\n",
            "\n",
            "16. Indonesia to ban social media and other online platforms for under 16s\n",
            "   URL: https://www.bbc.com/news/articles/cvg50168ddgo?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: Indonesia preparing to deploy up to 8,000 soldiers to Gaza\n",
            "\n",
            "It would be the first country to do so as part of phase two of the ceasefire agreement bro...\n",
            "------------------------------------------------------------\n",
            "\n",
            "17. US and Venezuela agree to resume diplomatic ties after Maduro capture\n",
            "   URL: https://www.bbc.com/news/articles/cy9g1l5jx90o?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: After a visit to Venezuela, US Secretary of the Interior Doug Burgum told reporters on the runway in Caracas on Thursday on his way back to the US tha...\n",
            "------------------------------------------------------------\n",
            "\n",
            "18. We've been speaking to Iranians during one week of war. Here's what they said\n",
            "   URL: https://www.bbc.com/news/articles/c5y5lqygrn7o?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: My colleague Ghoncheh Habibiazad, who has been collecting voices from inside the country, says the views of some people have changed as the war has co...\n",
            "------------------------------------------------------------\n",
            "\n",
            "19. The heartwarming tale of a father, a daughter, and a wedding band wowing India\n",
            "   URL: https://www.bbc.com/news/articles/c7430kn9ze4o?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: \"It's not a matter of shame for the father,\" Rao says. \"He wants to welcome her back with the same pomp and show with which he had sent her off. By ce...\n",
            "------------------------------------------------------------\n",
            "\n",
            "20. The final voyage of the Iranian warship sunk by the US\n",
            "   URL: https://www.bbc.com/news/articles/c4geelnw7w3o?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: \"What happened next is less clear: the ship may have returned to port or peeled away after exercises. Either way, the waters where it was later sunk -...\n",
            "------------------------------------------------------------\n",
            "\n",
            "21. AI-generated Iran war videos surge as creators use new tech to cash in\n",
            "   URL: https://www.bbc.com/news/articles/ckg8wvz427vo?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: Experts have told BBC Verify that while many social media companies say they are trying to change their moderation and detection systems to address th...\n",
            "------------------------------------------------------------\n",
            "\n",
            "22. Beirut evacuees 'sleeping in tents and cars'\n",
            "   URL: https://www.bbc.com/news/videos/cg4g0gl23z4o?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: In Lebanon, some residents in the southern Beirut suburb of Dahieh have left their homes amid evacuation orders and ongoing air strikes by Israel.\n",
            "\n",
            "BB...\n",
            "------------------------------------------------------------\n",
            "\n",
            "23. After Iran, will Trump turn his eyes to Cuba?\n",
            "   URL: https://www.bbc.com/news/videos/c4gq8yd3qlxo?at_medium=RSS&at_campaign=rss\n",
            "   Text preview: Donald Trump's attention is seemingly turning to another Latin American regime: Cuba.\n",
            "\n",
            "In recent months, the president has hinted at a possible takeov...\n",
            "------------------------------------------------------------\n",
            "\n",
            "✨ Scraping complete!\n"
          ]
        }
      ]
    }
  ]
}